"""Added new tables, deleted columns, added new columns

Revision ID: 412c3e4afd22
Revises: 3508c8dc6439
Create Date: 2023-09-21 14:53:45.481170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412c3e4afd22'
down_revision = '3508c8dc6439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_schedules_coach_id_coaches')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crossfit_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_crossfit_classes_coach_id_coaches', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_crossfit_classes_schedule_id_schedules'), 'schedules', ['schedule_id'], ['id'])
        batch_op.drop_column('coach_id')
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crossfit_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('coach_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_crossfit_classes_schedule_id_schedules'), type_='foreignkey')
        batch_op.create_foreign_key('fk_crossfit_classes_coach_id_coaches', 'coaches', ['coach_id'], ['id'])
        batch_op.drop_column('schedule_id')

    op.drop_table('schedules')
    # ### end Alembic commands ###
