"""Adding Schedule and schedule_workout table object

Revision ID: 4badf4446a42
Revises: 891260f22eaa
Create Date: 2023-09-22 14:02:11.855285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4badf4446a42'
down_revision = '891260f22eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_workout_plans',
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_workout_plans_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], name=op.f('fk_schedule_workout_plans_workout_plan_id_workout_plans')),
    sa.PrimaryKeyConstraint('workout_plan_id', 'schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_workout_plans')
    op.drop_table('schedules')
    # ### end Alembic commands ###
