"""Connected Coach to Schedule

Revision ID: 7ad2f0fafda4
Revises: 5398047355a5
Create Date: 2023-09-22 14:46:12.644300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad2f0fafda4'
down_revision = '5398047355a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_schedules_coach_id_coaches'), 'coaches', ['coach_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_schedules_coach_id_coaches'), type_='foreignkey')
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###
