"""broke my db. starting from scratch. Coach table and 3 related tables

Revision ID: 891260f22eaa
Revises: 
Create Date: 2023-09-22 12:24:20.076805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891260f22eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('focus', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crossfit_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_move_id', sa.Integer(), nullable=True),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_move_id'], ['exercise_moves.id'], name=op.f('fk_crossfit_classes_exercise_move_id_exercise_moves')),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], name=op.f('fk_crossfit_classes_workout_plan_id_workout_plans')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crossfit_classes')
    op.drop_table('workout_plans')
    op.drop_table('exercise_moves')
    op.drop_table('coaches')
    # ### end Alembic commands ###
