"""Removed table object. Using Schedule as association model

Revision ID: fc0d22234886
Revises: 7ad2f0fafda4
Create Date: 2023-09-22 21:21:03.036998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0d22234886'
down_revision = '7ad2f0fafda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_workout_plans')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_schedules_workout_plan_id_workout_plans'), 'workout_plans', ['workout_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_schedules_workout_plan_id_workout_plans'), type_='foreignkey')
        batch_op.drop_column('workout_plan_id')

    op.create_table('schedule_workout_plans',
    sa.Column('workout_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='fk_schedule_workout_plans_schedule_id_schedules'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], name='fk_schedule_workout_plans_workout_plan_id_workout_plans'),
    sa.PrimaryKeyConstraint('workout_plan_id', 'schedule_id')
    )
    # ### end Alembic commands ###
